// Regenerate the static 2026 almanac data used by both calendar editions.
// Run: npm install lunar-javascript@1.7.7 --no-save && node generate-almanac.cjs
// Source: https://github.com/6tail/lunar-javascript (MIT, 6tail, 2018).
const fs = require("node:fs");
const path = require("node:path");
const { Solar } = require("lunar-javascript");

const entries = {};
for (let month = 1; month <= 12; month++) {
  const days = new Date(2026, month, 0).getDate();
  for (let day = 1; day <= days; day++) {
    const key = `${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
    const lunar = Solar.fromYmd(2026, month, day).getLunar();
    entries[key] = [lunar.getDayYi(), lunar.getDayJi()];
  }
}
const heading = "// 2026 daily 宜/忌 from lunar-javascript v1.7.7 (MIT; © 2018 6tail).\n" +
  "// Generated by generate-almanac.cjs; no runtime dependency or network request.\n" +
  "// Traditional almanac editions can differ. These entries are for creative analogy, not advice.\n";
const content = heading + "const ALMANAC_2026 = " + JSON.stringify(entries, null, 2) + ";\n";
fs.writeFileSync(path.join(__dirname, "almanac-2026.js"), content, "utf8");
console.log(`Wrote ${Object.keys(entries).length} daily entries.`);
