// Hand-written analogies from traditional almanac activities to optional research activities.
// [English source label, Chinese research action, English research action]
const RESEARCH_MAP = {
  "祭祀": ["ceremonial observance", "举办项目致谢会", "hold a project appreciation session"],
  "出行": ["travel", "外出参加学术会议", "travel to an academic conference"],
  "安葬": ["burial", "归档已结束的研究项目", "archive a completed research project"],
  "嫁娶": ["marriage", "敲定长期科研合作", "formalize a long-term collaboration"],
  "安床": ["setting a bed", "调整实验室工位", "rearrange the lab workspace"],
  "动土": ["breaking ground", "启动新实验", "launch a new experiment"],
  "祈福": ["praying for blessings", "提交基金申请", "submit a grant proposal"],
  "开光": ["consecration", "公开展示新研究工具", "demonstrate a new research tool"],
  "破土": ["excavation", "开辟新研究方向", "open a new line of inquiry"],
  "移徙": ["relocation", "迁移代码仓库", "migrate a code repository"],
  "解除": ["removing obstacles", "清理积压的技术债", "clear accumulated technical debt"],
  "修造": ["construction", "重构研究代码", "refactor research code"],
  "入宅": ["moving into a home", "部署新研究环境", "deploy a new research environment"],
  "立券": ["signing a deed", "签署合作协议", "sign a collaboration agreement"],
  "入殓": ["preparing for burial", "封存结项实验记录", "seal completed experiment records"],
  "纳采": ["formal proposal", "投稿论文", "submit a manuscript"],
  "交易": ["exchange", "商定数据使用协议", "agree on a data-use arrangement"],
  "求嗣": ["seeking offspring", "提出下一轮研究问题", "propose the next research question"],
  "开市": ["opening a market", "发布项目主页", "launch a project website"],
  "拆卸": ["dismantling", "拆解旧实验流程", "dismantle an old experiment workflow"],
  "出火": ["moving the hearth fire", "迁移计算任务", "move a compute workload"],
  "栽种": ["planting", "启动长期观测", "start a longitudinal study"],
  "订盟": ["making an alliance", "确定合作分工", "agree on collaborator roles"],
  "纳畜": ["bringing in livestock", "扩充设备资源池", "expand the equipment pool"],
  "上梁": ["raising the main beam", "搭建论文主体结构", "build the main paper outline"],
  "启钻": ["beginning excavation", "深挖一个关键结果", "investigate a key result in depth"],
  "会亲友": ["meeting friends and family", "与合作者线下交流", "meet collaborators in person"],
  "移柩": ["moving a coffin", "迁移历史项目档案", "move historical project archives"],
  "除服": ["ending mourning attire", "结束项目复盘阶段", "close a project review phase"],
  "成服": ["beginning mourning attire", "启动项目复盘阶段", "begin a project review phase"],
  "进人口": ["welcoming household members", "迎接新成员入组", "welcome a new lab member"],
  "起基": ["laying foundations", "搭建研究基础设施", "set up research infrastructure"],
  "纳财": ["receiving funds", "整理项目经费预算", "prepare a project budget"],
  "沐浴": ["bathing", "整理研究工作区", "tidy the research workspace"],
  "冠笄": ["coming-of-age ceremony", "完成项目阶段验收", "complete a project milestone review"],
  "安门": ["installing a door", "设置数据访问权限", "set data access permissions"],
  "牧养": ["tending animals", "维护长期数据集", "maintain a longitudinal dataset"],
  "挂匾": ["hanging a plaque", "发布成果介绍页", "publish a research showcase page"],
  "塞穴": ["sealing openings", "修补数据处理漏洞", "patch a data-processing gap"],
  "理发": ["haircut", "精简冗余代码", "trim redundant code"],
  "扫舍": ["cleaning the home", "清理实验目录", "clean up experiment directories"],
  "竖柱": ["raising pillars", "建立评价指标", "establish evaluation metrics"],
  "结网": ["making a net", "梳理合作网络", "map a collaboration network"],
  "坏垣": ["demolishing a wall", "移除过时的分析假设", "remove an obsolete analysis assumption"],
  "盖屋": ["building a house", "搭建论文框架", "build a manuscript structure"],
  "破屋": ["demolishing a house", "淘汰旧实验流程", "retire an old experiment workflow"],
  "立碑": ["setting a marker", "记录项目里程碑", "record a project milestone"],
  "伐木": ["cutting timber", "删减无效研究分支", "prune an unproductive research branch"],
  "谢土": ["thanking the earth after building", "完成项目收尾与致谢", "close out a project with acknowledgements"],
  "作灶": ["building a stove", "配置计算环境", "configure a computing environment"],
  "畋猎": ["hunting", "检索潜在研究对象", "search for candidate study subjects"],
  "治病": ["treating illness", "安排非紧急系统大修", "schedule non-urgent system maintenance"],
  "安香": ["placing incense", "举行项目启动仪式", "hold a project kickoff"],
  "裁衣": ["tailoring clothes", "调整论文版式", "revise manuscript formatting"],
  "平治道涂": ["leveling roads", "梳理数据处理流程", "streamline the data-processing pipeline"],
  "修坟": ["maintaining a grave", "整理历史项目档案", "organize historical project archives"],
  "捕捉": ["catching", "收集实验异常案例", "collect anomalous experiment cases"],
  "补垣": ["mending a wall", "补齐方法文档", "fill gaps in methods documentation"],
  "修饰垣墙": ["repairing walls", "打磨论文图表边界", "refine manuscript figures"],
  "塑绘": ["painting figures", "绘制研究示意图", "draw a research schematic"],
  "掘井": ["digging a well", "开辟新数据来源", "develop a new data source"],
  "经络": ["weaving threads", "梳理变量关系", "map relationships between variables"],
  "开仓": ["opening a storehouse", "开放研究数据仓库", "open a research data repository"],
  "赴任": ["taking office", "接手新研究任务", "take on a new research assignment"],
  "斋醮": ["ritual observance", "安排组内专题研讨", "hold a focused lab discussion"],
  "造桥": ["building a bridge", "建立跨学科合作", "build a cross-disciplinary collaboration"],
  "词讼": ["litigation", "发起署名争议仲裁", "initiate an authorship dispute review"],
  "探病": ["visiting the sick", "安排非紧急系统巡检", "schedule a non-urgent system inspection"],
  "置产": ["acquiring property", "采购长期研究设备", "purchase long-term research equipment"],
  "造船": ["building a boat", "搭建新数据采集平台", "build a new data-collection platform"],
  "作梁": ["making beams", "重写论文核心论证", "rebuild the manuscript's core argument"],
  "行丧": ["funeral rites", "举行项目结束复盘会", "hold an end-of-project review"],
  "开渠": ["opening a channel", "建立数据同步通道", "establish a data-sync channel"],
  "出货财": ["shipping goods", "移交研究数据包", "transfer a research data package"],
  "开池": ["digging a pond", "建立实验样本池", "set up an experiment sample pool"],
  "开厕": ["building a latrine", "处理实验废弃物流程", "update the lab waste workflow"],
  "针灸": ["acupuncture", "做定点性能优化", "make a targeted performance fix"],
  "分居": ["separating households", "拆分耦合过深的项目", "split an overly coupled project"],
  "合帐": ["setting up a canopy", "搭建临时实验工作区", "set up a temporary experiment workspace"],
  "造庙": ["building a shrine", "建设项目知识库", "build a project knowledge base"],
  "安碓磑": ["installing milling equipment", "安装数据处理设备", "install data-processing equipment"],
  "立柱": ["raising a pillar", "建立研究基线", "establish a research baseline"],
  "造仓": ["building a storehouse", "建设数据归档库", "build a data archive"],
  "造畜稠": ["building an animal shelter", "扩建仪器存放区", "expand the equipment storage area"],
  "教牛马": ["training work animals", "培训新仪器操作", "train the team on new equipment"],
  "造车器": ["making a vehicle", "组装实验装置", "assemble an experimental apparatus"],
  "安机械": ["installing machinery", "安装实验仪器", "install laboratory equipment"],
  "开生坟": ["preparing a future burial site", "预建项目归档目录", "prepare a future project archive"],
  "取渔": ["fishing", "筛选候选样本", "screen candidate samples"],
  "定磉": ["setting foundation stones", "锁定研究基线", "lock in a research baseline"],
  "放水": ["releasing water", "开放数据接口", "open a data interface"],
  "入学": ["starting school", "开启新方法学习", "begin studying a new method"],
  "问名": ["inquiring after a name", "核实合作者信息", "verify collaborator details"],
  "整手足甲": ["grooming nails", "整理实验细节", "tidy up experimental details"],
  "雇佣": ["hiring", "招募研究助理", "recruit a research assistant"],
  "求医": ["seeking medical help", "请求技术支持", "seek technical support"],
  "合寿木": ["assembling a coffin", "封装结项资料", "package completed-project records"],
  "筑堤": ["building an embankment", "建立数据质量防线", "build data-quality safeguards"],
  "架马": ["preparing a horse", "准备外场研究设备", "prepare fieldwork equipment"],
  "开柱眼": ["drilling beam joints", "打通工作流接口", "connect workflow interfaces"],
  "纳婿": ["welcoming a son-in-law", "邀请长期合作者加入", "invite a long-term collaborator"],
  "修门": ["repairing a door", "检修数据访问入口", "repair a data access gateway"],
  "断蚁": ["removing ants", "排查细碎异常", "investigate small anomalies"],
  "习艺": ["learning a craft", "练习新分析方法", "practice a new analysis method"],
  "割蜜": ["harvesting honey", "汇总阶段性研究成果", "collect interim research results"],
  "归岫": ["returning to a resting place", "将旧项目移回档案库", "return an old project to the archive"],
  "雕刻": ["carving", "打磨模型细节", "refine model details"],
  "普渡": ["communal rites", "组织公开研究交流", "host an open research exchange"],
  "合脊": ["joining a roof ridge", "合并研究分支", "merge research branches"],
  "乘船": ["travel by boat", "开展水上外场采样", "conduct field sampling on water"],
  "归宁": ["visiting one's family", "回访原合作团队", "revisit a former collaborator team"],
  "诸事不宜": ["no undertaking advised", "暂缓启动高风险新任务", "defer a high-risk new undertaking"],
  "馀事勿取": ["no other undertaking advised", "只处理既定研究任务", "stick to already planned research tasks"]
};

// A source prohibition needs an avoidable action, not a prohibition of caution itself.
const RESEARCH_DONT_OVERRIDE = {
  "诸事不宜": ["贸然启动额外高风险任务", "start an unplanned high-risk undertaking"],
  "词讼": ["仓促升级署名争议", "escalate an authorship dispute in haste"]
};

// Prefer concrete terms with a useful research analogy; ties keep source order.
const ALMANAC_SKIP = new Set(["馀事勿取", "诸事不宜", "无"]);
const ALMANAC_PRIORITY = {
  "纳采": 11, "谢土": 10, "开市": 9, "交易": 9, "立券": 9, "修造": 9, "纳财": 8,
  "动土": 8, "出行": 8, "入宅": 8, "起基": 8, "赴任": 8, "习艺": 8,
  "订盟": 7, "解除": 7, "会亲友": 7, "开仓": 7, "求嗣": 7,
  "安门": 6, "竖柱": 6, "上梁": 6, "平治道涂": 6, "沐浴": 5,
  "祭祀": 1, "嫁娶": 1, "安葬": 1, "入殓": 1, "移柩": 1
};
function mappedEntries(labels, count = 2) {
  const matches = labels.filter(label => !ALMANAC_SKIP.has(label) && RESEARCH_MAP[label]);
  if (matches.length) return matches.sort((a, b) => (ALMANAC_PRIORITY[b] || 3) - (ALMANAC_PRIORITY[a] || 3)).slice(0, count);
  const qualified = labels.find(label => RESEARCH_MAP[label]);
  return qualified ? [qualified] : [];
}
